name: Gradle Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean Gradle
        run: ./gradlew cleanBuildCache

      - name: Run tests and Generate Code Coverage
        run: |
          ./gradlew jacocoTestReport
          ./gradlew connectedCheck
          
      - name: Publish Code Coverage to codecov
        run: bash <(curl -s https://codecov.io/bash) -X fix
