name: Gradle Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests and Generate Code Coverage
        run: ./gradlew jacocoTestReleaseUnitTestReport
        
      - name: Rewrite Base Path in coverage
        run: sed 's/com\/imagekit\/android/imagekit\/src\/main\/java\/com\/imagekit\/android/g' imagekit/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml > imagekit/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml
        
      - name: Upload Coverage file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: imagekit/build/reports/jacoco/jacocoTestReleaseUnitTestReport/jacocoTestReleaseUnitTestReport.xml
        
      - name: Publish Code Coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)
